---
awesome-bar:
  description: Configuring the awesome bar.
  hasExposure: true
  exposureDescription: ""
  variables:
    min-search-term:
      type: int
      description: The minimum number of characters that the user types before searching in the page.
    position:
      type: json
      description: "This property defines whether or not the feature is enabled, and the position of the search bar\n"
    search-highlights:
      type: boolean
      description: Whether or not search highlights are enabled
    use-page-content:
      type: boolean
      description: "Search in the open tab's text content when typing."
general-app-features:
  description: The feature that contains feature flags for the entire application
  hasExposure: true
  exposureDescription: ""
  variables:
    pull-to-refresh:
      type: json
      description: This property defines whether or not the feature is enabled
    report-site-issue:
      type: json
      description: This property defines whether or not the feature is enabled
    shake-to-restore:
      type: json
      description: This property defines whether or not the feature is enabled
homescreenFeature:
  description: The homescreen that the user goes to when they press home or new tab.
  hasExposure: true
  exposureDescription: ""
  variables:
    sections-enabled:
      type: json
      description: "This property provides a lookup table of whether or not the given section should be enabled. If the section is enabled, it should be toggleable in the settings screen, and on by default.\n"
    sponsored-tiles:
      type: json
      description: "This property defines the sponsored tile feature on the homepage, which is not a section therein.\n"
    wallpaper-feature:
      type: json
      description: "This property defines the wallpaper feature on the homepage, which is not a section therein.\n"
messaging:
  description: "Configuration for the messaging system.\nIn practice this is a set of growable lookup tables for the message controller to piece together.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    actions:
      type: json
      description: A growable map of action URLs.
    message-under-experiment:
      type: string
      description: Id or prefix of the message under experiment.
    messages:
      type: json
      description: "A growable collection of messages, where the Key is the message identifier and the value is its associated MessageData."
    on-control:
      type: string
      description: What should be displayed when a control message is selected.
      enum:
        - show-next-message
        - show-none
    styles:
      type: json
      description: "A map of styles to configure message appearance.\n"
    triggers:
      type: json
      description: "A collection of out the box trigger expressions. Each entry maps to a valid JEXL expression.\n"
search-term-groups-feature:
  description: The feature that controls whether or not search term groups are enabled.
  hasExposure: true
  exposureDescription: ""
  variables:
    grouping-enabled:
      type: json
      description: This property provides a lookup table of whether or not the given grouping should be enabled.
spotlight-search:
  description: "Add of webpages to iOS's core search."
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: Add pages as items findable with Spotlight.
    icon-type:
      type: string
      description: "The icon that is displayed next to the item in the search results. If this is `null`, then no icon is displayed.\n"
    keep-for-days:
      type: int
      description: "Number of days to keep the item before automatic deletion. If this is left `null`, then it is left to iOS's default.\n"
    searchable-content:
      type: string
      description: "The text content that is made searchable. If this is `null` then no additional content is used, and only the title and URL will be used.\n"
start-at-home-feature:
  description: The controls for Start at Home feature
  hasExposure: true
  exposureDescription: ""
  variables:
    setting:
      type: string
      description: This property provides a default setting for the startAtHomeFeature
      enum:
        - always
        - disabled
        - after-four-hours
tabTrayFeature:
  description: The tab tray screen that the user goes to when they open the tab tray.
  hasExposure: true
  exposureDescription: ""
  variables:
    sections-enabled:
      type: json
      description: "This property provides a lookup table of whether or not the given section should be enabled. If the section is enabled, it should be toggleable in the settings screen, and on by default."
