queue_rules:
  - name: default
    conditions:
      - check-success=Bitrise

pull_request_rules:
  - name: Resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request has conflicts when rebasing. Could you fix it @{{author}}?
  - name: github-actions
    conditions:
      - author=github-actions[bot]
      - files~=(bitrise.yml)
    actions:
      review:
        type: APPROVE
        message: Github-action[bot] 💪
      queue:
        method: rebase
        name: default
  - name: String Import - Auto Approve
    conditions:
      - author=github-actions[bot]
      - title~=string-import*
      - or:
        - files~=^Client\/[^\/]*\/[^\/]*.lproj\/*
        - files~=^Client\/[^\/]*.lproj\/*
        - files~=^Shared\/[^\/]*\/[^\/]*.lproj\/*
        - files~=^Shared\/[^\/]*.lproj\/*
        - files~=^WidgetKit\/[^\/]*\/[^\/]*.lproj\/*
        - files~=^WidgetKit\/[^\/]*.lproj\/*
    actions:
      review:
        type: APPROVE
        message: Automatically approving string import
  - name: String Import - Auto Merge
    conditions:
      - author=github-actions[bot]
      - title~=string-import*
      - or:
        - files~=^Client\/[^\/]*\/[^\/]*.lproj\/*
        - files~=^Client\/[^\/]*.lproj\/*
        - files~=^Shared\/[^\/]*\/[^\/]*.lproj\/*
        - files~=^Shared\/[^\/]*.lproj\/*
        - files~=^WidgetKit\/[^\/]*\/[^\/]*.lproj\/*
        - files~=^WidgetKit\/[^\/]*.lproj\/*
    actions:
      queue:
        method: rebase
        name: default
