disabled_rules: # rule identifiers to exclude from running
# These rules were originally disabled. Leaving them separate
# just in case, but they will each be looked at in turn.
- variable_name
- type_name
- function_body_length
- missing_docs
- valid_docs
- cyclomatic_complexity
- type_body_length
- function_parameter_count
- weak_delegate
- discarded_notification_center_observer
- fallthrough

# Disabled all default rules
- block_based_kvo
- class_delegate_protocol
- closing_brace
- closure_parameter_position
- comma
- comment_spacing
- compiler_protocol_init
- computed_accessors_order
- control_statement
- custom_rules
- deployment_target
- discouraged_direct_init
- duplicate_enum_cases
- duplicate_imports
- duplicated_key_in_dictionary_literal
- dynamic_inline
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- file_length
- for_where
- force_cast
- force_try
- generic_type_name
- identifier_name
- implicit_getter
- inclusive_language
- inert_defer
- is_disjoint
- large_tuple
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_hashing
- legacy_nsgeometry_functions
- legacy_random
- line_length
- mark
- multiple_closures_with_trailing_closure
- nesting
- no_fallthrough_only
- no_space_in_method_call
- notification_center_detachment
- nsobject_prefer_isequal
- opening_brace
- operator_whitespace
- orphaned_doc_comment
- private_over_fileprivate
- private_unit_test
- protocol_property_accessors_order
- reduce_boolean
- redundant_discardable_let
- redundant_objc_attribute
- redundant_optional_initialization
- redundant_set_access_control
- redundant_string_enum_value
- redundant_void_return
- return_arrow_whitespace
- self_in_property_initialization
- shorthand_operator
- statement_position
- superfluous_disable_command
- switch_case_alignment
- syntactic_sugar
- todo
- trailing_comma
- trailing_newline
- trailing_semicolon
- trailing_whitespace
- type_body_length
- unneeded_break_in_switch
- unused_capture_list
- unused_closure_parameter
- unused_control_flow_label
- unused_enumerated
- unused_optional_binding
- unused_setter_value
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_whitespace
- void_return
- xctfail_message

opt_in_rules: # some rules are only opt-in
# These rules were originally opted into. Disabling for now to get
# Swiftlint up and running.
  # - closing_brace
  # - opening_brace
  # - return_arrow_whitespace
  # - trailing_semicolon
  # - statement_position
  # - explicit_init
  # - file_header
  # - deployment_target
  # - discouraged_optional_collection
  # - duplicate_imports
  # - empty_string
  # - overridden_super_call
  # - prohibited_interface_builder
  # - prohibited_super_call
  # - protocol_property_accessors_order
  # - redundant_objc_attribute
  # - redundant_type_annotation
  # - unused_import
  # Find all the available rules by running:
  # swiftlint rules

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - ThirdParty
  - FxA
  - FxAClient
  - build
  - Storage/ThirdParty/SwiftData.swift
  - UITests/
  - XCUITests/
  - fastlane/
  - Client/Assets/Search/get_supported_locales.swift
  - Client/Generated

# reporter: "json" # reporter type (xcode, json, csv, checkstyle)
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
