osx_image: xcode611
language: objective-c
script:
  - brew update
  - brew upgrade xctool
  - brew install carthage
  - carthage update --no-build
  - xcodebuild -project Client.xcodeproj -scheme Travis -configuration Debug -destination "platform=iOS Simulator,OS=8.1,name=iPhone 6" clean test

# This stopped working
#  - xctool -project Client.xcodeproj -scheme Travis -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
#  - xctool test -freshSimulator -project Client.xcodeproj -scheme Travis -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
