---
trust-domain: mobile
treeherder:
    group-names:
        I: Docker Image Builds
        B: Builds

task-priority: highest

taskgraph:
    register: ffios_taskgraph:register
    repositories:
        mobile:
            name: "Firefox for iOS"
    cached-task-prefix: mobile.v2.firefox-ios
    decision-parameters: ffios_taskgraph.parameters:get_decision_parameters

workers:
    aliases:
        bitrise:
            provisioner: scriptworker-k8s
            implementation: scriptworker-bitrise
            os: scriptworker
            worker-type: mobile-{level}-bitrise
        images:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'images-gcp'
        b-macos:
            provisioner: 'releng-hardware'
            implementation: generic-worker
            os: macosx
            worker-type:
                by-level:
                    "3": 'mozilla-b-3-osx'
                    default: 'mozilla-b-1-osx'
        misc:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux-gcp'

scriptworker:
    scope-prefix: project:mobile:firefox-ios:releng
