name: code-cov

on:
  push:
    branches:
main
  pull_request:
    branches:
main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test
        run:  xcodebuild test -project Client.xcodeproj -scheme Fennec -destination 'platform=iOS Simulator,name=iPhone 13,OS=14.3' build test
