name: Automatic Update and Publish PR for Bitrise Steps
on: 
  schedule: 
    - cron: '0 */6 * * *'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Modify bitrise.yml
      run: |
        python ./test-fixtures/update.py
      - name: Commit and push if bitrise.yml changed
      run: |-
        git diff
        git config --global user.email "firefox-test-engineering@mozilla.com"
        git config --global user.name "Firefox Test Engineering"
        git diff --quiet || (git add bitrise.yml)
      - name: Auto Update Bitrise Steps Versions
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Auto Update Bitrise Steps Versions
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        committer: GitHub <noreply@github.com>
        title: Update Bitrise YML file with latest steps versions
        branch: update-br-new-steps-versions
        token: ${{ secrets.GITHUB_TOKEN }}