name: "Firefox Tests"
    
on:
    workflow_dispatch:

env:
    browser: firefox-ios
    xcode_version: 15.4
    ios_version: 17.5
    ios_simulator_default: iPhone 15
    xcodebuild_scheme: Fennec
    xcodebuild_target: Client
    test_results_directory: /Users/runner/tmp
    
jobs:
    compile:
        name: Compile
        runs-on: macos-14-xlarge
        steps:
            - name: Check out source code
              uses: actions/checkout@v4.1.7
            - name: Setup Xcode
              id: xcode
              run: |
                sudo rm -rf /Applications/Xcode.app
                sudo xcode-select -s /Applications/Xcode_${{ env.xcode_version }}.app/Contents/Developer
                xcodebuild -version
                ./checkout.sh
                ./bootstrap.sh --force
            - name: Compile source code
              id: compile
              run: |
                xcodebuild \
                  -resolvePackageDependencies \
                  -onlyUsePackageVersionsFromResolvedFile
                xcodebuild \
                  build-for-testing \
                  -scheme ${{ env.xcodebuild_scheme }} \
                  -target ${{ env.xcodebuild_target }} \
                  -derivedDataPath ~/DerivedData \
                  -destination 'platform=iOS Simulator,name=${{ env.ios_simulator_default }},OS=${{ env.ios_version }}'
              working-directory: ${{ env.browser }}
            - name: Compress Derived Data
              id: compress-dd
              run: |
                tar czf derived-data.tar.gz ~/DerivedData/Build/Products
            - name: Save Derived Data
              id: upload-derived-data
              uses: actions/upload-artifact@v4.3.4
              with:
                name: xcode-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}
                path: ./derived-data.tar.gz
                retention-days: 2
                
    run-fullfunctionaltests:
        name: Run full functional tests
        runs-on: macos-14-xlarge
        needs: compile
        strategy:
            fail-fast: false
            matrix:
                ios_simulator: ['iPhone 15 Plus']
        steps:
            - name: Check out source code
              uses: actions/checkout@v4.1.7
            - name: Install packages
              id: packages
              run: |
                gem install xcpretty -v 0.3.0
                pip install blockkit==1.9.1
                npm install -g junit-report-merger@7.0.0