name: Publish Leaks

on:
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app && /usr/bin/xcodebuild -version
   
      - name: Check xcodebuild
        run: xcodebuild -version

     